### ISSUE TITLE
wp_bb_* table names obsolete

### ISSUE THREAD

**Issue by SHOP-DEV** [boonebgorges/Import-from-Ning#3]
Plugin references obsolete tables `wp_bb_topics` and `wp_bb_posts` which I believe are both in the `$wpdb->posts` table now. The plugin fails to import topics because the prefix is hardcoded and the tables no longer exist.

**Comment by boonebgorges** [comment]
Thanks for the report. You're correct that the table names are obsolete in bbPress 2+. This part of the importer should be disabled for sites running that version of bbPress, and a new importer should be written for bbPress 2.0+. I haven't got the ability to do this at the moment, but if anyone sends a PR, I'll be glad to review it.
